use mavenmovies;
-- Q1. retrieve the total number of rentals made in the sakila database?? --
select count(*) customer_id from rental;
-- Q2. find the average rental duration(in days) of movies rented from the sakila database?? --
select avg(rental_duration) from film;
-- Q3. Display the first name and last name of customer in uppercase?? --
select upper(first_name),(last_name)from customer;
-- Q4. Extract the month from rental date and display it alongside the rental ID?? --
Select rental_id, month(rental_date) from rental;
-- Q5. Retrieve the count of rentals for each customer(display customer ID and the count of rentals)?? --
select customer_id , count(rental_id) from rental group by customer_id;  
-- Q6. Find the total revenue generated by each store?? --
select sum(amount) as total_revenue from payment;
-- Q7. Display the title of the movie , customer's first name and last name who rented it?? --
select title , first_name , last_name from film , customer inner join rental on rental.customer_id=customer.customer_id;
-- Q8. Retrieve the names of all actors who have appeared in the film 'Gone Trouble'?? --
select first_name , last_name from actor inner join film_actor on actor.actor_id=film_actor.actor_id inner join film on film_actor.film_id=film.film_id;
-- Q9. Determine the total number of rentals for each category of movies?? --
select category_id , count(rental_id) from film_category , payment group by category_id;
-- Q10. Find the average rental rate of movies in each Language?? --
select avg(rental_rate) , language_id from film , language;